### ISSUE TITLE
Script stopped working (with data) after 8.2.7 Splunk upgrade

### ISSUE THREAD

**Issue by qlmradoszewski** [cameronjust/TA-base64#2]
Good day @cameronjust!

It seems like the script stopped working with the 8.2.7 Splunk update.
It returns "Streamed search execute failed because: Error in 'script': Getinfo probe failed for external search command 'base64'." for all of our searches.

I have checked it with the usual query we used for version 2.x of the app:

`| makeresults
| eval encodedField = "ZnJlZA==", otherEncodedField="YmFycnkK"
| base64 action=decode field=encodedField mode=append
| base64 action=decode field=otherEncodedField mode=append
| eval toEncode = "this is to be encoded"
| base64 action=encode field=toEncode mode=append
| table _time encodedField* otherEncodedField* *`

And it works as expected but when we feed it with actual data we are experiencing this error.

I was trying to debug it and after some time I have found out that:

`index=cdn 
| eval OTT_RollingBuffer = "ZnJlZA=="
| base64 field=OTT_RollingBuffer action=decode mode=replace`

returns the error

while:
`|makeresults 
| eval OTT_RollingBuffer = "ZnJlZA=="
| base64 field=OTT_RollingBuffer action=decode mode=replace`

is working as intended.

Fetching the actual data from actual index breaks it somehow.

Maybe some libraries changed again and requires updating to include the latest splunklib again or maybe that's some kind of  permissions problem as |makeresults works just fine?

We would really appreciate some help with this issue if you are able to look into that.

**Comment by cameronjust** [comment]
I just updated lib/splunklib with the latest version from Splunk and it seems to be working with the search you provided on Splunk 9.0.0

https://github.com/splunk/splunk-sdk-python

Let me know if that helps.

**Comment by qlmradoszewski** [comment]
Good day @cameronjust Just letting you know that after updating the libraries the script works as expected again. Thank you for your support!

**Comment by qlmradoszewski** [comment]
Resolved by updating the libraries.

**Comment by cameronjust** [comment]
No problems.

I reworked the whole app to pass appinspect as well if you want to grab the latest version on github.
